[pytest]
env =
    DB_USER=product_owner
    DB_PASSWORD=ownerpassword
    DB_HOST=localhost
    DB_PORT=5432
    DB_NAME=produtos_db
    DATABASE_URL=postgresql://product_owner:ownerpassword@localhost:5432/produtos_db